---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef
  become_method: sudo

  tasks:
#    - name: Reboot the system
#      ansible.builtin.reboot:
#        reboot_timeout: 600

    - name: Reboot the machine via shell
      ansible.builtin.shell: |
        sleep 2 && /sbin/shutdown -r now "Reboot triggered by Ansible"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait a bit for reboot to trigger (optional)
      ansible.builtin.pause:
        seconds: 5

    - name: Create an empty file after triggering reboot
      ansible.builtin.file:
        path: /home/ec2-user/hi
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: '0644'