---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef

  tasks:
    - name: Delete Podman
      ansible.builtin.dnf:
        name: podman
        state: absent
      become: true

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600
