---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef
  become_method: sudo

  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600
