---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef
  become_method: sudo

  tasks:
#    - name: Reboot the system
#      ansible.builtin.reboot:
#        reboot_timeout: 600

    - name: Reboot the machine via shell
      ansible.builtin.shell: |
        sleep 2 && /sbin/shutdown -r now "Reboot triggered by Ansible"
