---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef
  become_method: sudo

  tasks:
#    - name: Reboot the system
#      ansible.builtin.reboot:
#        reboot_timeout: 600

    - name: Reboot system asynchronously
      ansible.builtin.shell: sleep 2 && /sbin/shutdown -r now "Reboot by Ansible"
      async: 60
      poll: 5
      ignore_errors: true

    - name: Wait for system to become reachable again (up to 5 minutes)
      ansible.builtin.wait_for_connection:
        delay: 10           # Wait 10 seconds before first check
        timeout: 300        # Total wait time = 5 minutes
      register: wait_result
      retries: 3
      delay: 10             # Retry every 10 seconds
      until: wait_result is success

    - name: Create an empty file after triggering reboot
      ansible.builtin.file:
        path: /home/ec2-user/hi
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: '0644'