---
- name: jg-test
  hosts: "{{ _hosts | default(omit) }}"
  vars:
    volume_path: podman
    message: undef

  tasks:
    - name: Install Podman
      ansible.builtin.dnf:
        name: podman
        state: installed
      become: true
